### ISSUE TITLE
Incorrect collisions detection

### ISSUE THREAD

**Issue by Saied-Basha** [corehtml5canvas/code#11]
In example-8.10, try to update the 1st polygon points to:
[ new Point(25.5, 100), new Point(200.5, 200),
        new Point(400.5, 200), new Point(600.5, 160), 
		new Point(600.5, 300), new Point(16.5, 300) ]
If you dragged any other polygon between the 1st polygon faced edges without real intersection, it will detect collision while there is no collision
![detectcollisionissue](https://cloud.githubusercontent.com/assets/10911350/11562198/1b5fbbd2-99d5-11e5-867a-998c308bbfe0.JPG)

**Comment by corehtml5canvas** [comment]
See the book's discussion of the Separating Axis Theorem, which is the collision detection algorithm used in the example you site. The SAT only works for convex shapes. The shape you have created is concave, and therefore will not work with the SAT.

**Comment by Saied-Basha** [comment]
Thanks, got the note "NOTE: Convex polygons only" at page 495
sorry for interruption

**Comment by corehtml5canvas** [comment]
No problem. Thanks for being involved!
