### ISSUE TITLE
example-1.4:line 86 the third parameter did not used?

### ISSUE THREAD

**Issue by arthurlee** [corehtml5canvas/code#12]
```javascript
   function drawHand(loc, isHour) {
       // ...
   }

     // ...
   function drawHands() {
       // ...
       drawHand(hour*5 + (date.getMinutes()/60)*5, true, 0.5);
       drawHand(date.getMinutes(), false, 0.5);
       drawHand(date.getSeconds(), false, 0.2);
   }
```

I cannot find how the third parameter is used? Did it mean the length of the hand?

**Comment by delhanty** [comment]
I just found the same thing too when converting the examples to Typescript.

Perhaps the 3rd parameter is meant to be the width of the hand.  Anyway, it is not used.

**Comment by IEEEkuldeep** [comment]
function drawHand(loc, isHour) {
       // ...
   }

     // ...
   function drawHands() {
       // ...
       drawHand(hour*5 + (date.getMinutes()/60)*5, true, 0.5);
       drawHand(date.getMinutes(), false, 0.5);
       drawHand(date.getSeconds(), false, 0.2);
   }

**Comment by corehtml5canvas** [comment]
The third parameter is not used. I believe delhanty is correct. It originally was used for the length of the hand.
